#!/bin/bash
if [ $# -lt 3 ]; then
	echo "usage:  ./query <SmartContract> <Function> <args> "
	echo "Note that args need to be an array of strings, with ESCAPED quotes. "
	echo "Example: ./query fabric-authtoken readAuthToken [\"test\"] "
	exit 1
fi
CHANNEL_ID=mychannel
source peer_vars.sh
FUNCTION=$2
SMARTCONTRACT=$1
ARGS=$3
echo -e "Querying $FUNCTION of $SMARTCONTRACT on $CHANNEL_ID with $ARGS"
peer chaincode query -C $CHANNEL_ID -n $SMARTCONTRACT -c "{\"function\": \"$FUNCTION\", \"Args\": $ARGS}"
